/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/scene.gltf 
Author: RPSebb (https://sketchfab.com/RPSebb)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/chocolate-cake-7a1c5357e44b4c63993d7842b188047a
Title: Chocolate Cake
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const ChocolateCake = (props) => {
  const { nodes, materials } = useGLTF('./models/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.081}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cake_Cake_Baked_0.geometry} material={materials.Cake_Baked} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/scene.gltf')

export default ChocolateCake;